"use client"
import PriceFilter from "@/components/price-filter"
import { useState, useEffect, useCallback } from "react"
import Link from "next/link"
import { ChevronLeft, ChevronRight } from "lucide-react"
import MemberLayout from "@/components/member-layout"

// Define publication data structure
interface Publication {
  name: string
  initials: string
  genres: string[]
  price: number
  da: number
  dr: number
  tat: string
  region: string
  sponsored: "Yes" | "No" | "Discrete"
  indexed: "Yes" | "No"
  doFollow: "Yes" | "No"
}

// Generate publications with real names
const generatePublications = (): Publication[] => {
  const publicationNames = [
    "Celebrity News",
    "CEO Weekly",
    "World Reporter",
    "Hood Critic",
    "Daily Scanner",
    "Film Daily",
    "Tech Bullion",
    "Medium",
    "Elite Luxury News",
    "Kivo Daily",
    "Luxury Travel Magazine",
    "MetaPress",
    "Providr",
    "US Reporter",
    "US Insider",
    "Futuristic Architecture",
    "Dubai Weekly",
    "Vents Magazine",
    "Mark Meets",
    "Cryptonexa",
    "Tech Today",
    "Business Insider Pro",
    "Fashion Forward",
    "Sports Chronicle",
    "Crypto Daily",
    "Health & Wellness Today",
    "Travel Enthusiast",
    "Gaming Universe",
    "Food & Dining",
    "Science Today",
    "The New York Times",
    "The Washington Post",
    "The Wall Street Journal",
    "USA Today",
    "Los Angeles Times",
    "Chicago Tribune",
    "The Boston Globe",
    "The Guardian",
    "The Times",
    "The Telegraph",
    "The Independent",
    "Financial Times",
    "Bloomberg",
    "Reuters",
    "Associated Press",
    "Forbes",
    "Fortune",
    "Business Week",
    "The Economist",
    "Time Magazine",
    "Newsweek",
    "The Atlantic",
    "The New Yorker",
    "Vanity Fair",
    "Wired",
    "National Geographic",
    "Scientific American",
    "Popular Science",
    "Popular Mechanics",
    "MIT Technology Review",
    "TechCrunch",
    "Engadget",
    "Gizmodo",
    "CNET",
    "The Verge",
    "Mashable",
    "VentureBeat",
    "Ars Technica",
    "ZDNet",
    "PCMag",
    "Vogue",
    "Elle",
    "Harper's Bazaar",
    "GQ",
    "Esquire",
    "Men's Health",
    "Women's Health",
    "Cosmopolitan",
    "Glamour",
    "InStyle",
    "Rolling Stone",
    "Billboard",
    "Pitchfork",
    "NME",
    "Spin",
    "ESPN",
    "Sports Illustrated",
    "The Athletic",
    "Bleacher Report",
    "SB Nation",
    "Food & Wine",
    "Bon Appétit",
    "Epicurious",
    "Eater",
    "Serious Eats",
    "Travel + Leisure",
    "Condé Nast Traveler",
    "Lonely Planet",
    "Fodor's",
    "Frommer's",
    "Architectural Digest",
    "Dwell",
    "Dezeen",
    "Design Milk",
    "Apartment Therapy",
    "The Hollywood Reporter",
    "Variety",
    "Entertainment Weekly",
    "Deadline",
    "Screen Rant",
    "IGN",
    "Polygon",
    "Kotaku",
    "GameSpot",
    "PC Gamer",
    "WebMD",
    "Healthline",
    "Medical News Today",
    "Psychology Today",
    "Self",
    "Nature",
    "Science",
    "PNAS",
    "Cell",
    "The Lancet",
    "Harvard Business Review",
    "McKinsey Quarterly",
    "Strategy+Business",
    "Sloan Management Review",
    "Inc.",
    "Fast Company",
    "Entrepreneur",
    "AdWeek",
    "Ad Age",
    "MarketingWeek",
    "Social Media Examiner",
    "Buffer",
    "Hootsuite",
    "Sprout Social",
    "Later",
    "Search Engine Journal",
    "Search Engine Land",
    "Moz",
    "SEMrush",
    "Ahrefs",
    "Smashing Magazine",
    "A List Apart",
    "CSS-Tricks",
    "Codrops",
    "SitePoint",
    "Digital Trends",
    "Tom's Guide",
    "Tom's Hardware",
    "AnandTech",
    "TechRadar",
    "Android Authority",
    "9to5Mac",
    "9to5Google",
    "MacRumors",
    "AppleInsider",
    "Windows Central",
    "The Next Web",
    "ReadWrite",
    "Lifehacker",
    "How-To Geek",
    "Apartment Therapy",
    "Houzz",
    "HGTV",
    "Better Homes & Gardens",
    "Real Simple",
    "Good Housekeeping",
    "Martha Stewart Living",
    "Southern Living",
    "Cooking Light",
    "EatingWell",
    "The Kitchn",
    "Taste of Home",
    "Allrecipes",
    "Delish",
    "Epicurious",
    "Backpacker",
    "Outside",
    "Runner's World",
    "Bicycling",
    "Climbing",
    "Yoga Journal",
    "Shape",
    "Prevention",
    "Health",
    "Fitness",
    "Parents",
    "Parenting",
    "Family Circle",
    "Working Mother",
    "Today's Parent",
    "The Spruce",
    "WikiHow",
    "Instructables",
    "DIY Network",
    "Make:",
    "Investopedia",
    "The Motley Fool",
    "Kiplinger",
    "Barron's",
    "MarketWatch",
    "Morningstar",
    "Seeking Alpha",
    "Benzinga",
    "TheStreet",
    "Zacks",
    "CoinDesk",
    "Cointelegraph",
    "Bitcoin Magazine",
    "Decrypt",
    "The Block",
    "Vox",
    "Slate",
    "Salon",
    "HuffPost",
    "BuzzFeed News",
    "Vice",
    "Quartz",
    "Business Insider",
    "The Daily Beast",
    "Axios",
    "FiveThirtyEight",
    "ProPublica",
    "The Intercept",
    "Mother Jones",
    "The Nation",
    "Foreign Policy",
    "Foreign Affairs",
    "The Diplomat",
    "World Politics Review",
    "International Affairs",
    "Harvard Law Review",
    "Yale Law Journal",
    "Stanford Law Review",
    "Columbia Law Review",
    "NYU Law Review",
    "American Bar Association Journal",
    "Law360",
    "Above the Law",
    "SCOTUSblog",
    "Jurist",
    "Chronicle of Higher Education",
    "Inside Higher Ed",
    "Education Week",
    "The Journal of Higher Education",
    "Harvard Educational Review",
    "Science News",
    "Discover",
    "New Scientist",
    "Physics Today",
    "Chemical & Engineering News",
    "Astronomy",
    "Sky & Telescope",
    "Space.com",
    "Universe Today",
    "Planetary Society",
    "Psychology Today",
    "American Psychologist",
    "Journal of Personality and Social Psychology",
    "Psychological Science",
    "Clinical Psychology Review",
    "JAMA",
    "New England Journal of Medicine",
    "BMJ",
    "The Lancet",
    "Nature Medicine",
    "IEEE Spectrum",
    "Communications of the ACM",
    "Journal of Machine Learning Research",
    "AI Magazine",
    "Robotics & Automation Magazine",
    "Linux Journal",
    "Linux Magazine",
    "Ubuntu User",
    "LWN.net",
    "It's FOSS",
    "Game Developer",
    "Gamasutra",
    "Game Informer",
    "Edge",
    "Game Studies",
    "Animation Magazine",
    "Animation World Network",
    "Cartoon Brew",
    "3D World",
    "ImagineFX",
    "Digital Photography Review",
    "PetaPixel",
    "Fstoppers",
    "SLR Lounge",
    "Shutterbug",
    "Modern Drummer",
    "Guitar World",
    "Bass Player",
    "Keyboard Magazine",
    "Electronic Musician",
    "Mix",
    "Sound on Sound",
    "Audio Media International",
    "Resolution",
    "Tape Op",
    "Filmmaker Magazine",
    "American Cinematographer",
    "MovieMaker",
    "Film Comment",
    "Sight & Sound",
    "Adbusters",
    "Communication Arts",
    "Print",
    "Eye",
    "Graphis",
    "Juxtapoz",
    "Hi-Fructose",
    "Beautiful/Decay",
    "Colossal",
    "This Is Colossal",
    "Artforum",
    "ARTnews",
    "Art in America",
    "Frieze",
    "Hyperallergic",
    "Wallpaper*",
    "Metropolis",
    "Azure",
    "Interior Design",
    "Frame",
    "Car and Driver",
    "Road & Track",
    "Motor Trend",
    "Automobile",
    "AutoWeek",
    "Robb Report",
    "Departures",
    "Town & Country",
    "Tatler",
    "W Magazine",
    "Wine Spectator",
    "Wine Enthusiast",
    "Decanter",
    "Whisky Advocate",
    "Beer Advocate",
    "Saveur",
    "Food & Wine",
    "Gourmet",
    "Bon Appétit",
    "Cook's Illustrated",
    "Gardening Australia",
    "Fine Gardening",
    "Garden Design",
    "Horticulture",
    "The Garden",
    "Outdoor Life",
    "Field & Stream",
    "Sports Afield",
    "Guns & Ammo",
    "Shooting Times",
    "Yachting",
    "Boating",
    "Sail",
    "Cruising World",
    "Power & Motoryacht",
    "Flying",
    "AOPA Pilot",
    "Plane & Pilot",
    "Aviation Week",
    "Air & Space",
    "Trains",
    "Model Railroader",
    "Railway Age",
    "International Railway Journal",
    "Railway Gazette",
    "Cycle World",
    "Motorcyclist",
    "Rider",
    "Motorcycle.com",
    "RevZilla",
    "Hot Rod",
    "Car Craft",
    "Street Rodder",
    "Rod & Custom",
    "Super Chevy",
    "Four Wheeler",
    "Off-Road",
    "4x4",
    "Overland Journal",
    "Expedition Portal",
    "Snowboarder",
    "Transworld Snowboarding",
    "Powder",
    "Ski",
    "Freeskier",
    "Surfer",
    "Surfing",
    "The Surfer's Journal",
    "Stab",
    "Tracks",
    "Thrasher",
    "Transworld Skateboarding",
    "The Skateboard Mag",
    "Jenkem",
    "Kingpin",
    "Golf Digest",
    "Golf Magazine",
    "Golfweek",
    "Golf World",
    "Links",
    "Tennis",
    "Tennis Magazine",
    "World Tennis",
    "Racquet",
    "Baseline",
    "Triathlete",
    "Triathlon Magazine",
    "220 Triathlon",
    "Lava",
    "Triathlon Plus",
    "Climbing",
    "Rock and Ice",
    "Alpinist",
    "Gripped",
    "Climber",
    "Backpacker",
    "Hiking",
    "Trail Runner",
    "Adventure Journal",
    "Wilderness",
    "Scuba Diving",
    "Dive",
    "Sport Diver",
    "X-Ray Mag",
    "Underwater Photography",
    "Canoe & Kayak",
    "Paddling Magazine",
    "Sea Kayaker",
    "Rapid",
    "American Whitewater",
    "Fly Fisherman",
    "Fly Tyer",
    "American Angler",
    "Fly Fishing & Tying Journal",
    "Trout",
    "Bassmaster",
    "In-Fisherman",
    "Bass Angler",
    "FLW Outdoors",
    "Wired2Fish",
    "Deer & Deer Hunting",
    "North American Whitetail",
    "Bowhunter",
    "Bowhunting World",
    "Petersen's Bowhunting",
    "Waterfowl",
    "Wildfowl",
    "Duck Unlimited",
    "Game & Fish",
    "Outdoor Life",
    "Turkey Country",
    "Turkey & Turkey Hunting",
    "Turkey Call",
    "Grand Slam Network",
    "NWTF",
    "Predator Xtreme",
    "Predator Nation",
    "Varmint Hunter",
    "Fur-Fish-Game",
    "Trapper & Predator Caller",
    "Successful Farming",
    "Progressive Farmer",
    "Farm Journal",
    "Corn and Soybean Digest",
    "No-Till Farmer",
    "Beef",
    "Drovers",
    "Cattle Today",
    "Angus Journal",
    "Hereford World",
    "National Hog Farmer",
    "Pork",
    "Pig Progress",
    "Pig International",
    "The Pig Site",
    "Poultry Times",
    "Poultry World",
    "Egg Industry",
    "The Poultry Site",
    "WATTPoultry",
    "Dairy Herd Management",
    "Progressive Dairyman",
    "Hoard's Dairyman",
    "Dairy Today",
    "The Bullvine",
    "Western Horseman",
    "Horse & Rider",
    "Practical Horseman",
    "Dressage Today",
    "The Chronicle of the Horse",
    "Hobby Farms",
    "Acres USA",
    "Small Farm Today",
    "Growing for Market",
    "Modern Farmer",
    "Astronomy",
    "Sky & Telescope",
    "Astronomy Now",
    "Amateur Astronomy",
    "Celestial Observer",
    "Woodworking",
    "Fine Woodworking",
    "Popular Woodworking",
    "Woodsmith",
    "Wood Magazine",
    "Quilting Arts",
    "Quiltmaker",
    "American Patchwork & Quilting",
    "McCall's Quilting",
    "Fons & Porter's Love of Quilting",
    "Interweave Knits",
    "Vogue Knitting",
    "Knitter's Magazine",
    "Knit Simple",
    "Knitting",
    "Threads",
    "Sew News",
    "Vogue Patterns",
    "Burda Style",
    "Sew Today",
    "Bead & Button",
    "Beadwork",
    "Stringing",
    "Bead Style",
    "Jewelry Artist",
    "Ceramics Monthly",
    "Pottery Making Illustrated",
    "Clay Times",
    "Ceramic Review",
    "Studio Potter",
    "American Craft",
    "Craft",
    "Make:",
    "Craft & Design",
    "Handmade Business",
    "Lapidary Journal Jewelry Artist",
    "Rock & Gem",
    "Gems & Gemology",
    "The Mineralogical Record",
    "Rocks & Minerals",
    "Coin World",
    "Numismatic News",
    "Coins Magazine",
    "World Coin News",
    "Coin Prices",
    "Linn's Stamp News",
    "Scott Stamp Monthly",
    "American Philatelist",
    "Stamp Magazine",
    "Gibbons Stamp Monthly",
    "Antique Trader",
    "Maine Antique Digest",
    "Antiques & The Arts Weekly",
    "The Magazine Antiques",
    "Antique Collecting",
    "Doll Reader",
    "Doll News",
    "Contemporary Doll Collector",
    "Antique Doll Collector",
    "Dolls Magazine",
    "Teddy Bear & Friends",
    "Teddy Bear Times",
    "Teddy Bear Club International",
    "Teddy Bear Review",
    "Teddy Bear Artist Invitational",
    "Miniature Collector",
    "Dollhouse Miniatures",
    "American Miniaturist",
    "Dolls House World",
    "Dolls House and Miniature Scene",
    "Toy Collector Magazine",
    "Toy Shop",
    "Toys & Prices",
    "Toy Trader",
    "Action Figure Digest",
    "Sports Collectors Digest",
    "Sports Card Monthly",
    "Beckett Sports Card Monthly",
    "Sports Collectors Journal",
    "Trading Card Times",
    "Comic Shop News",
    "Comic Buyer's Guide",
    "Wizard",
    "Comics Journal",
    "Alter Ego",
    "Military Trader",
    "Military Vehicles Magazine",
    "Military History",
    "MHQ: The Quarterly Journal of Military History",
    "Armchair General",
    "Gun Digest",
    "Firearms News",
    "American Rifleman",
    "Guns Magazine",
    "Combat Handguns",
    "Knife Magazine",
    "Blade",
    "Knives Illustrated",
    "Tactical Knives",
    "American Blade",
    "Classic Car",
    "Hemmings Motor News",
    "Classic & Sports Car",
    "Classic Cars",
    "Vintage Motorsport",
    "Cigar Aficionado",
    "Smoke",
    "Cigar Journal",
    "Cigar Press",
    "Cigar Snob",
    "Whisky Advocate",
    "Whisky Magazine",
    "The Whiskey Wash",
    "Distiller",
    "Bourbon Review",
    "Wine Spectator",
    "Wine Enthusiast",
    "Decanter",
    "Wine Advocate",
    "Vinous",
    "Beer Advocate",
    "All About Beer",
    "Draft",
    "Craft Beer & Brewing",
    "Beer Connoisseur",
    "Imbibe",
    "Punch",
    "Chilled",
    "Bartender",
    "Difford's Guide",
    "Coffee Review",
    "Barista Magazine",
    "Fresh Cup",
    "Roast",
    "Coffee Talk",
    "Tea Time",
    "Tea Magazine",
    "World Tea News",
    "Tea Journey",
    "Tea & Coffee Trade Journal",
    "Chocolatier",
    "Chocolate Connoisseur",
    "Candy Industry",
    "Confection Connection",
    "Sweet",
    "Vegetarian Times",
    "VegNews",
    "Vegetarian Journal",
    "Vegan Life",
    "Plant Based News",
    "Gluten-Free Living",
    "Living Without's Gluten Free & More",
    "Simply Gluten Free",
    "Gluten-Free & More",
    "The Celiac Scene",
    "Paleo Magazine",
    "Paleo Times",
    "Paleo Lifestyle Magazine",
    "Caveman Feast",
    "Paleo Diet News",
    "Keto Life",
    "Keto Connect",
    "Keto Magazine",
    "Keto Diet",
    "Ketogenic Living",
    "Organic Life",
    "Organic Gardening",
    "Organic Farming",
    "Organic Matters",
    "Organic Lifestyle Magazine",
    "Clean Eating",
    "Eating Clean",
    "Clean Food",
    "Whole Foods Magazine",
    "Natural Health",
    "Yoga Journal",
    "Yoga Magazine",
    "Om Yoga",
    "Yoga International",
    "Yoga Today",
    "Mindful",
    "Mindfulness",
    "Breathe",
    "Calm",
    "Present",
    "Spirituality & Health",
    "Watkins Mind Body Spirit",
    "Spiritual Magazine",
    "Light of Consciousness",
    "Science of Mind",
    "Tricycle",
    "Lion's Roar",
    "Buddhadharma",
    "Buddhism Now",
    "Shambhala Sun",
    "Hinduism Today",
    "Hinduism Magazine",
    "Hindu Voice",
    "Hindu Today",
    "Hinduism World",
    "Tikkun",
    "Moment",
    "Jewish Review of Books",
    "Jewish Quarterly",
    "Jewish Action",
    "America",
    "First Things",
    "Christianity Today",
    "Christian Century",
    "Sojourners",
    "The Islamic Monthly",
    "Azizah",
    "Islamic Horizons",
    "Muslim Matters",
    "The Muslim Vibe",
    "Pagan Dawn",
    "Witches & Pagans",
    "The Pomegranate",
    "Sage Woman",
    "PanGaia",
    "New Age Journal",
    "New Dawn",
    "Nexus",
    "Atlantis Rising",
    "Mysteries Magazine",
    "Paranormal Review",
    "Fortean Times",
    "Fate",
    "Paranormal Magazine",
    "Ghost Voices",
    "UFO Magazine",
    "MUFON Journal",
    "Open Minds",
    "UFO Truth Magazine",
    "UFO Digest",
    "Cryptozoology Review",
    "Bigfoot Times",
    "Cryptid Culture",
    "Strange Magazine",
    "Cryptozoology News",
    "Astrology Magazine",
    "The Mountain Astrologer",
    "Horoscope Guide",
    "Dell Horoscope",
    "Prediction",
    "Tarot Magazine",
    "The Cartomancer",
    "Tarosophist International",
    "Tarot Professionals",
    "Tarot Elements",
    "Numerology Magazine",
    "Numerology Today",
    "Numerology World",
    "Number Patterns",
    "Numerological Insights",
    "Dream Network",
    "Dream Time",
    "Dream Chronicles",
    "Dream Interpretation",
    "Lucid Dreaming Experience",
    "Reiki News Magazine",
    "Reiki Magazine",
    "Reiki Rays",
    "Reiki Times",
    "Reiki Digest",
    "Energy Magazine",
    "Energy Times",
    "Energy Healing",
    "Subtle Energy",
    "Healing Touch",
    "Crystal Magazine",
    "Crystal Healing",
    "Crystal Life",
    "Crystal Enlightenment",
    "Crystal Wisdom",
    "Feng Shui Magazine",
    "Feng Shui World",
    "Feng Shui Times",
    "Feng Shui Life",
    "Feng Shui Journal",
    "Tiny House Magazine",
    "Small House Bliss",
    "Tiny Living",
    "Small Home",
    "Micro Living",
    "Minimalist Magazine",
    "Minimalism Life",
    "Simple Living",
    "Less is More",
    "Minimal Matter",
    "Zero Waste Magazine",
    "Trash is for Tossers",
    "Zero Waste Life",
    "Waste Not",
    "Plastic Free",
    "Sustainable Living",
    "Green Living",
    "Eco Living",
    "Earth Conscious",
    "Planet Friendly",
    "Permaculture Magazine",
    "Permaculture Design",
    "Permaculture News",
    "Permaculture Works",
    "Permaculture Activist",
    "Homesteading Today",
    "Homestead Magazine",
    "Modern Homesteading",
    "Self-Reliance",
    "Backwoods Home",
    "Off Grid Living",
    "Off Grid World",
    "Off Grid Life",
    "Living Off the Grid",
    "Self Sufficient",
    "Prepper Magazine",
    "Survival Dispatch",
    "Survival Quarterly",
    "American Survival Guide",
    "OFFGRID",
    "Mother Earth News",
    "Grit",
    "Countryside",
    "Backwoods Home",
    "Self-Reliance",
    "Utne Reader",
    "Yes!",
    "Adbusters",
    "The Sun",
    "Orion",
    "The Baffler",
    "n+1",
    "McSweeney's",
    "Granta",
    "The Paris Review",
    "Tin House",
    "Ploughshares",
    "The Iowa Review",
    "The Kenyon Review",
    "The Southern Review",
    "Poetry",
    "American Poetry Review",
    "Poets & Writers",
    "The Writer's Chronicle",
    "Rattle",
    "Writer's Digest",
    "The Writer",
    "Poets & Writers",
    "Creative Nonfiction",
    "Writer's Forum",
    "Literary Hub",
    "Electric Literature",
    "The Millions",
    "Book Riot",
    "Literary Review",
    "New York Review of Books",
    "London Review of Books",
    "Times Literary Supplement",
    "The Believer",
    "Bookforum",
    "Publishers Weekly",
    "Kirkus Reviews",
    "Library Journal",
    "Booklist",
    "School Library Journal",
    "Horn Book Magazine",
    "Children's Book Review",
    "Bulletin of the Center for Children's Books",
    "VOYA",
    "Book Links",
    "The Comics Journal",
    "Comic Book Creator",
    "Alter Ego",
    "Back Issue",
    "Comic Book Artist",
    "Animation Magazine",
    "Animation World",
    "Skwigly",
    "Animation Reporter",
    "Animation Express",
    "Filmmaker Magazine",
    "MovieMaker",
    "Film Comment",
    "Cineaste",
    "Sight & Sound",
    "American Cinematographer",
    "ICG Magazine",
    "British Cinematographer",
    "Canadian Cinematographer",
    "Australian Cinematographer",
    "Mix",
    "Sound & Vision",
    "Audio Media International",
    "Resolution",
    "Pro Sound News",
    "Electronic Musician",
    "Future Music",
    "Computer Music",
    "Music Tech",
    "Sound on Sound",
    "Billboard",
    "Rolling Stone",
    "Spin",
    "NME",
    "Mojo",
    "Pitchfork",
    "The Wire",
    "Downbeat",
    "JazzTimes",
    "Jazzwise",
    "Classical Music",
    "Gramophone",
    "BBC Music Magazine",
    "Opera News",
    "Choir & Organ",
    "Alternative Press",
    "Kerrang!",
    "Metal Hammer",
    "Revolver",
    "Decibel",
    "DJ Mag",
    "Mixmag",
    "Resident Advisor",
    "EDM",
    "Dance Music Northwest",
    "Hip Hop DX",
    "XXL",
    "The Source",
    "Vibe",
    "Complex",
    "Country Weekly",
    "Nash Country Daily",
    "Country Music",
    "Taste of Country",
    "Country Universe",
    "Bluegrass Today",
    "Bluegrass Unlimited",
    "Bluegrass Now",
    "Bluegrass Music Profiles",
    "The Bluegrass Standard",
    "Folk Alley",
    "Folk Roots",
    "Sing Out!",
    "fRoots",
    "Folk Radio UK",
    "World Music",
    "Songlines",
    "fRoots",
    "Global Rhythm",
    "Afropop Worldwide",
    "Reggae Report",
    "Reggae Vibes",
    "United Reggae",
    "Reggae Festival Guide",
    "Reggae Times",
    "Blues Music Magazine",
    "Living Blues",
    "Blues Blast Magazine",
    "Blues Matters!",
    "Blues & Rhythm",
    "Punk Planet",
    "Maximum Rocknroll",
    "Razorcake",
    "Punk News",
    "Punk Globe",
    "Prog",
    "Classic Rock",
    "Uncut",
    "Record Collector",
    "Shindig!",
    "Vintage Guitar",
    "Guitar Player",
    "Guitar World",
    "Guitarist",
    "Total Guitar",
    "Bass Player",
    "Bass Magazine",
    "Bass Musician Magazine",
    "Bass Gear Magazine",
    "No Treble",
    "Modern Drummer",
    "Drum!",
    "Rhythm",
    "Drummer",
    "Drumhead",
    "Keyboard Magazine",
    "Keyboard Player",
    "Keys",
    "Clavier Companion",
    "Piano Today",
    "The Strad",
    "Strings",
    "Fiddler Magazine",
    "Acoustic Guitar",
    "Classical Guitar",
    "Brass Band World",
    "British Bandsman",
    "4barsrest",
    "Brass Herald",
    "Brass Review",
    "Double Reed",
    "The Clarinet",
    "Saxophone Journal",
    "Flute Talk",
    "Pan: The Flute Magazine",
    "Choral Journal",
    "The Voice",
    "Choral Director",
    "Teaching Music",
    "Music Educators Journal",
    "Opera News",
    "Opera Now",
    "Opera Magazine",
    "Opera Today",
    "Opera Wire",
    "Musical Theatre Magazine",
    "The Sondheim Review",
    "Show Music",
    "Stage Directions",
    "Playbill",
    "American Theatre",
    "Theatre Journal",
    "Theatre Topics",
    "Theatre Research International",
    "Theatre Survey",
    "Dance Magazine",
    "Pointe",
    "Dance Spirit",
    "Dance Teacher",
    "Dancing Times",
    "Variety",
    "The Hollywood Reporter",
    "Deadline Hollywood",
    "Screen International",
    "The Wrap",
    "Empire",
    "Total Film",
    "Premiere",
    "Film Comment",
    "Little White Lies",
    "Cinefex",
    "VFX Voice",
    "3D World",
    "CG World",
    "Animation World Network",
    "TV Guide",
    "Entertainment Weekly",
    "TV Line",
    "Television Business International",
    "Broadcasting & Cable",
    "Script Magazine",
    "Creative Screenwriting",
    "Written By",
    "Final Draft",
    "Fade In",
    "Backstage",
    "Actors Ink",
    "Dramatics",
    "The Actor's Market",
    "Casting Frontier",
    "Filmmaker",
    "IndieWire",
    "No Film School",
    "Film Courage",
    "Filmmaker IQ",
    "Box Office",
    "The Numbers",
    "Screen Daily",
    "Film Journal International",
    "Exhibitor Relations",
    "Film Art",
    "Film Quarterly",
    "Cinema Journal",
    "Screen",
    "Journal of Film and Video",
    "Film History",
    "Historical Journal of Film, Radio and Television",
    "Journal of Popular Film and Television",
    "New Review of Film and Television Studies",
    "Studies in French Cinema",
    "Journal of Japanese & Korean Cinema",
    "Asian Cinema",
    "Senses of Cinema",
    "Bright Lights Film Journal",
    "Film International",
    "Film Criticism",
    "Cineaste",
    "Film Comment",
    "Sight & Sound",
    "Cahiers du Cinéma",
    "Filmmaker",
    "MovieMaker",
    "American Cinematographer",
    "ICG Magazine",
    "British Cinematographer",
    "Mix",
    "Sound & Vision",
    "Pro Sound News",
    "Resolution",
    "Audio Media International",
    "Post Magazine",
    "Creative COW",
    "StudioDaily",
    "Digital Video",
    "Videomaker",
    "Wired",
    "Fast Company",
    "Inc.",
    "Entrepreneur",
    "Harvard Business Review",
    "Forbes",
    "Fortune",
    "Bloomberg Businessweek",
    "The Economist",
    "Barron's",
    "Wall Street Journal",
    "Financial Times",
    "Investor's Business Daily",
    "MarketWatch",
    "Kiplinger's Personal Finance",
    "Money",
    "Worth",
    "Smart Money",
    "Personal Finance",
    "Financial Planning",
    "Accounting Today",
    "Journal of Accountancy",
    "The CPA Journal",
    "Strategic Finance",
    "Management Accounting Quarterly",
    "Harvard Law Review",
    "Yale Law Journal",
    "Columbia Law Review",
    "Stanford Law Review",
    "University of Chicago Law Review",
    "American Bar Association Journal",
    "The National Law Journal",
    "The American Lawyer",
    "Corporate Counsel",
    "Law Practice",
    "HR Magazine",
    "Workforce",
    "Human Resource Executive",
    "People Management",
    "Talent Management",
    "Training",
    "Chief Learning Officer",
    "TD: Talent Development",
    "Learning Solutions",
    "Training Industry",
    "Supply Chain Management Review",
    "Logistics Management",
    "Inbound Logistics",
    "Supply & Demand Chain Executive",
    "Material Handling & Logistics",
    "Manufacturing Engineering",
    "Industry Week",
    "Manufacturing Business Technology",
    "Manufacturing Today",
    "Manufacturing Global",
    "Quality",
    "Quality Progress",
    "Quality Digest",
    "Quality Magazine",
    "ASQ Six Sigma Forum Magazine",
    "Occupational Health & Safety",
    "EHS Today",
    "Safety+Health",
    "Professional Safety",
    "Industrial Safety & Hygiene News",
    "Environmental Leader",
    "GreenBiz",
    "Environmental Business International",
    "Waste360",
    "Recycling Today",
    "Chemical & Engineering News",
    "Chemical Engineering",
    "Chemical Processing",
    "Chemistry World",
    "Chemical Week",
    "Pharmaceutical Executive",
    "Pharmaceutical Technology",
    "Pharmaceutical Commerce",
    "Pharmaceutical Manufacturing",
    "Pharmaceutical Business Review",
    "Medical Device & Diagnostic Industry",
    "Medical Product Manufacturing News",
    "Medical Design Technology",
    "Medical Design Briefs",
    "Medical Manufacturing Technology",
    "Food Engineering",
    "Food Processing",
    "Food Manufacturing",
    "Food Technology",
    "Food Quality & Safety",
    "Beverage Industry",
    "Beverage World",
    "BevNet",
    "Beverage Dynamics",
    "Drinks International",
    "Packaging World",
    "Packaging Digest",
    "Package Design",
    "Flexible Packaging",
    "Packaging Technology Today",
    "Plastics Technology",
    "Plastics News",
    "Plastics Engineering",
    "Plastics Today",
    "Plastics Design & Manufacturing",
    "Modern Machine Shop",
    "Manufacturing Engineering",
    "Cutting Tool Engineering",
    "Tooling & Production",
    "American Machinist",
    "Automation World",
    "Control Engineering",
    "Automation",
    "Industrial Automation",
    "Control Design",
    "Design News",
    "Machine Design",
    "Product Design & Development",
    "Design Engineering",
    "Engineering Design",
    "Electronic Design",
    "EDN",
    "EE Times",
    "Electronic Products",
    "Electronics Weekly",
    "Power Electronics",
    "Power Electronics Technology",
    "Power Systems Design",
    "Power Electronics News",
    "How2Power Today",
    "Microwave Journal",
    "Microwaves & RF",
    "High Frequency Electronics",
    "Microwave Product Digest",
    "RF Design",
    "Photonics Spectra",
    "Laser Focus World",
    "Optics & Photonics News",
    "EuroPhotonics",
    "BioPhotonics",
    "Vision Systems Design",
    "Quality Magazine",
    "Test & Measurement World",
    "Evaluation Engineering",
    "Quality Digest",
    "Sensors",
    "Sensors Online",
    "Sensor Technology",
    "Sensors & Transducers",
    "Sensor Review",
    "Embedded Systems Design",
    "Embedded Computing Design",
    "Embedded Systems Engineering",
    "RTC Magazine",
    "COTS Journal",
    "Communications of the ACM",
    "IEEE Computer",
    "IEEE Software",
    "IEEE Internet Computing",
    "IEEE Pervasive Computing",
    "Dr. Dobb's Journal",
    "SD Times",
    "Application Development Trends",
    "Visual Studio Magazine",
    ".NET Developer's Journal",
    "Java Developer's Journal",
    "JavaWorld",
    "Java Magazine",
    "JDJ",
    "Java Developer",
    "PHP Magazine",
    "php[architect]",
    "PHP Developer",
    "PHP Journal",
    "PHP Builder",
    "Python Magazine",
    "PyCon",
    "Python Journal",
    "Python Developer",
    "Pythonic",
    "Ruby Weekly",
    "RubyFlow",
    "Ruby Inside",
    "Ruby Journal",
    "Ruby Developer",
    "C/C++ Users Journal",
    "C++ Report",
    "C/C++ Developer",
    "C++ Journal",
    "C++ Builder",
    "Mobile Dev & Design",
    "App Developer Magazine",
    "Mobile Development Review",
    "Mobile Tech Today",
    "Mobile Enterprise",
    "Game Developer",
    "Gamasutra",
    "Game Informer",
    "Edge",
    "Game Studies",
    "Linux Journal",
    "Linux Magazine",
    "Linux Format",
    "Linux User & Developer",
    "Linux Pro Magazine",
    "Windows IT Pro",
    "Windows Developer",
    "Windows Magazine",
    "Windows Central",
    "Windows Report",
    "Mac|Life",
    "MacWorld",
    "Mac Format",
    "Mac Observer",
    "Mac Sources",
    "iOS Developer",
    "iOS Magazine",
    "iOS Central",
    "iOS Life",
    "iOS Today",
    "Android Magazine",
    "Android Central",
    "Android Developer",
    "Android Journal",
    "Android Authority",
    "Web Designer",
    "Web Developer",
    "Web Design Journal",
    "Web Design Ledger",
    "Webdesigner Depot",
    "UX Magazine",
    "UX Booth",
    "UX Matters",
    'UX Design  "Web Design Ledger',
    "Webdesigner Depot",
    "UX Magazine",
    "UX Booth",
    "UX Matters",
    "UX Design Edge",
    "UX Movement",
    "A List Apart",
    "Smashing Magazine",
    "CSS-Tricks",
    "Codrops",
    "SitePoint",
    "Digital Arts",
    "Computer Arts",
    "ImagineFX",
    "3D World",
    "3D Artist",
    "Photoshop User",
    "Photoshop Creative",
    "Advanced Photoshop",
    "Digital Camera World",
    "Digital Photographer",
    "Popular Photography",
    "Outdoor Photographer",
    "Digital Photo Pro",
    "Shutterbug",
    "Amateur Photographer",
    "Professional Photographer",
    "Rangefinder",
    "Photo District News",
    "British Journal of Photography",
    "Aperture",
    "Communication Arts",
    "Print",
    "How",
    "Graphis",
    "Eye",
    "Creative Review",
    "Computer Arts",
    "Digital Arts",
    "IdN",
    "Juxtapoz",
    "Adweek",
    "Advertising Age",
    "Campaign",
    "Marketing Week",
    "Brand Strategy",
    "PR Week",
    "PR News",
    "Public Relations Strategist",
    "Communication World",
    "Strategic Communication Management",
    "Event Marketer",
    "BizBash",
    "Special Events",
    "Event Solutions",
    "Event Planning News",
    "Chief Executive",
    "CEO Magazine",
    "Directors & Boards",
    "Corporate Board Member",
    "Directorship",
    "CFO",
    "Financial Executive",
    "Strategic Finance",
    "Treasury & Risk",
    "Controller's Report",
    "CIO",
    "InformationWeek",
    "Computerworld",
    "CIO Insight",
    "eWeek",
    "CSO",
    "Security",
    "SC Magazine",
    "Information Security",
    "Network Security",
    "CMO",
    "Chief Marketer",
    "Marketing Management",
    "Marketing News",
    "Marketing Insights",
    "Chief Learning Officer",
    "Training",
    "T+D",
    "Learning Solutions",
    "Workforce Development",
    "Chief Supply Chain Officer",
    "Supply Chain Management Review",
    "Supply Chain Quarterly",
    "Logistics Management",
    "Inbound Logistics",
  ]

  const basePublications = [
    {
      name: "Celebrity News",
      initials: "CN",
      genres: ["News", "Entertainment", "Fashion"],
      price: 250,
      da: 57,
      dr: 41,
      tat: "3-5 Days",
      region: "United States",
      sponsored: "Discrete" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "CEO Weekly",
      initials: "CW",
      genres: ["Business", "News", "Finance", "Leadership", "Tech"],
      price: 250,
      da: 60,
      dr: 71,
      tat: "3-5 Days",
      region: "United States",
      sponsored: "Discrete" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "World Reporter",
      initials: "WR",
      genres: ["News", "Politics", "Global"],
      price: 250,
      da: 56,
      dr: 43,
      tat: "3-5 Days",
      region: "United States",
      sponsored: "Discrete" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Hood Critic",
      initials: "HC",
      genres: ["Music"],
      price: 150,
      da: 11,
      dr: 24,
      tat: "1-3 Days",
      region: "United States, Utah",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Daily Scanner",
      initials: "DS",
      genres: ["News", "Tech", "Business", "Entertainment", "Lifestyle"],
      price: 150,
      da: 67,
      dr: 61,
      tat: "1 Day",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "No" as const,
    },
    // Add more publications as needed
    {
      name: "Film Daily",
      initials: "FD",
      genres: ["Entertainment"],
      price: 250,
      da: 64,
      dr: 73,
      tat: "1 Week",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Tech Bullion",
      initials: "TB",
      genres: ["Tech"],
      price: 200,
      da: 63,
      dr: 79,
      tat: "1 Week",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Medium",
      initials: "MD",
      genres: ["News"],
      price: 150,
      da: 95,
      dr: 94,
      tat: "1 Day",
      region: "Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "No" as const,
    },
    {
      name: "Elite Luxury News",
      initials: "EL",
      genres: ["Luxury", "Fashion", "Lifestyle", "Business", "News"],
      price: 200,
      da: 62,
      dr: 61,
      tat: "1-3 Days",
      region: "United States, Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Kivo Daily",
      initials: "KD",
      genres: ["Business", "Tech"],
      price: 250,
      da: 60,
      dr: 65,
      tat: "3-5 Days",
      region: "United States, Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Luxury Travel Magazine",
      initials: "LT",
      genres: ["Lifestyle", "Travel", "Luxury"],
      price: 250,
      da: 53,
      dr: 72,
      tat: "1-3 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "MetaPress",
      initials: "MP",
      genres: ["News", "Tech", "Web 3"],
      price: 200,
      da: 77,
      dr: 81,
      tat: "1-3 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Providr",
      initials: "PR",
      genres: ["News", "Entertainment"],
      price: 250,
      da: 71,
      dr: 45,
      tat: "1-3 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "US Reporter",
      initials: "UR",
      genres: ["News", "Business", "Tech", "Entertainment", "Lifestyle", "Politics"],
      price: 250,
      da: 56,
      dr: 62,
      tat: "3-5 Days",
      region: "Global",
      sponsored: "Discrete" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "US Insider",
      initials: "UI",
      genres: ["News", "Business", "Politics", "Tech"],
      price: 250,
      da: 57,
      dr: 59,
      tat: "3-5 Days",
      region: "Global",
      sponsored: "Discrete" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Futuristic Architecture",
      initials: "FA",
      genres: ["Real Estate", "Lifestyle", "Design"],
      price: 200,
      da: 77,
      dr: 62,
      tat: "3 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Dubai Weekly",
      initials: "DW",
      genres: ["News", "Business", "Luxury"],
      price: 200,
      da: 59,
      dr: 62,
      tat: "3 Days",
      region: "Middle East, UAE",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Vents Magazine",
      initials: "VM",
      genres: ["Music", "Entertainment", "Culture"],
      price: 160,
      da: 64,
      dr: 78,
      tat: "1-3 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Mark Meets",
      initials: "MM",
      genres: ["Music"],
      price: 200,
      da: 69,
      dr: 73,
      tat: "1 Day",
      region: "United Kingdom",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Cryptonexa",
      initials: "CN",
      genres: ["Web 3", "Tech", "Finance"],
      price: 200,
      da: 56,
      dr: 61,
      tat: "3-5 Days",
      region: "Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    // Add more publications to have at least 30 for pagination
    {
      name: "Tech Today",
      initials: "TT",
      genres: ["Tech", "News"],
      price: 180,
      da: 62,
      dr: 58,
      tat: "2-4 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Business Insider Pro",
      initials: "BI",
      genres: ["Business", "Finance"],
      price: 300,
      da: 85,
      dr: 82,
      tat: "5-7 Days",
      region: "Global",
      sponsored: "Discrete" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Fashion Forward",
      initials: "FF",
      genres: ["Fashion", "Lifestyle"],
      price: 220,
      da: 68,
      dr: 65,
      tat: "3-5 Days",
      region: "United States, Europe",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Sports Chronicle",
      initials: "SC",
      genres: ["Sports", "News"],
      price: 190,
      da: 59,
      dr: 61,
      tat: "2-4 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Crypto Daily",
      initials: "CD",
      genres: ["Web 3", "Finance", "Tech"],
      price: 230,
      da: 64,
      dr: 67,
      tat: "2-3 Days",
      region: "Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Health & Wellness Today",
      initials: "HW",
      genres: ["Health", "Lifestyle"],
      price: 175,
      da: 58,
      dr: 55,
      tat: "2-4 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Travel Enthusiast",
      initials: "TE",
      genres: ["Travel", "Lifestyle"],
      price: 210,
      da: 63,
      dr: 60,
      tat: "3-5 Days",
      region: "Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Gaming Universe",
      initials: "GU",
      genres: ["Gaming", "Tech", "Entertainment"],
      price: 185,
      da: 61,
      dr: 59,
      tat: "2-4 Days",
      region: "United States, Europe",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Food & Dining",
      initials: "FD",
      genres: ["Food", "Lifestyle"],
      price: 170,
      da: 57,
      dr: 54,
      tat: "2-3 Days",
      region: "United States",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
    {
      name: "Science Today",
      initials: "ST",
      genres: ["Science", "Tech", "News"],
      price: 240,
      da: 72,
      dr: 70,
      tat: "3-6 Days",
      region: "Global",
      sponsored: "No" as const,
      indexed: "Yes" as const,
      doFollow: "Yes" as const,
    },
  ]

  // Generate additional publications to reach 1100
  const additionalPublications: Publication[] = []
  const regions = ["United States", "Europe", "Asia", "Global", "United Kingdom", "Canada", "Australia", "Middle East"]
  const genres = [
    "News",
    "Business",
    "Tech",
    "Entertainment",
    "Lifestyle",
    "Music",
    "Fashion",
    "Sports",
    "Luxury",
    "Web 3",
    "Health",
    "Travel",
    "Gaming",
    "Food",
    "Science",
  ]
  const tats = ["1 Day", "2-3 Days", "3-5 Days", "1 Week", "5-7 Days"]
  const sponsoredOptions = ["Yes", "No", "Discrete"] as const
  const yesNoOptions = ["Yes", "No"] as const

  // Generate the remaining publications using real publication names
  for (let i = basePublications.length; i < 1100; i++) {
    const randomGenres = []
    const genreCount = Math.floor(Math.random() * 3) + 1 // 1-3 genres

    for (let j = 0; j < genreCount; j++) {
      const randomGenre = genres[Math.floor(Math.random() * genres.length)]
      if (!randomGenres.includes(randomGenre)) {
        randomGenres.push(randomGenre)
      }
    }

    // Use a real publication name from our list
    const nameIndex = i % publicationNames.length
    const name = publicationNames[nameIndex]

    // Generate initials from the name
    const initials = name
      .split(" ")
      .map((word) => word[0])
      .join("")
      .substring(0, 2) // Limit to 2 characters

    const price = Math.floor(Math.random() * 450) + 150 // 150-600
    const da = Math.floor(Math.random() * 40) + 55 // 55-95
    const dr = Math.floor(Math.random() * 40) + 55 // 55-95
    const tat = tats[Math.floor(Math.random() * tats.length)]
    const region = regions[Math.floor(Math.random() * regions.length)]
    const sponsored = sponsoredOptions[Math.floor(Math.random() * sponsoredOptions.length)]
    const indexed = yesNoOptions[Math.floor(Math.random() * yesNoOptions.length)]
    const doFollow = yesNoOptions[Math.floor(Math.random() * yesNoOptions.length)]

    additionalPublications.push({
      name,
      initials,
      genres: randomGenres,
      price,
      da,
      dr,
      tat,
      region,
      sponsored,
      indexed,
      doFollow,
    })
  }

  return [...basePublications, ...additionalPublications]
}

// Use the generated publications
const allPublications: Publication[] = generatePublications()

// Create best sellers list with a mix of low, mid, and high priced publications
const bestSellers = [
  // Low price range ($150-$180)
  ...allPublications.filter((p) => p.price >= 150 && p.price <= 180).slice(0, 7),
  // Mid price range ($181-$230)
  ...allPublications.filter((p) => p.price > 180 && p.price <= 230).slice(0, 7),
  // High price range ($231+)
  ...allPublications.filter((p) => p.price > 230).slice(0, 6),
].slice(0, 20)

// Categories
const categories = [
  { id: "best-sellers", name: "Best Sellers" },
  { id: "news", name: "News" },
  { id: "business", name: "Business" },
  { id: "tech", name: "Tech" },
  { id: "entertainment", name: "Entertainment" },
  { id: "lifestyle", name: "Lifestyle" },
  { id: "music", name: "Music" },
  { id: "fashion", name: "Fashion" },
  { id: "sports", name: "Sports" },
  { id: "luxury", name: "Luxury" },
  { id: "web3", name: "Web 3" },
  { id: "all", name: "All Publications" },
]

// Add this array for items per page options
const itemsPerPageOptions = [10, 20, 50, 100]

// In the PublicationsPage component, change the itemsPerPage from a constant to a state variable
export default function PublicationsPage() {
  const [activeCategory, setActiveCategory] = useState("best-sellers")
  const [maxPrice, setMaxPrice] = useState(5000)
  const [priceFilter, setPriceFilter] = useState(0) // Start with no price filter
  const [currentPage, setCurrentPage] = useState(1)
  const [searchQuery, setSearchQuery] = useState("")
  const [itemsPerPage, setItemsPerPage] = useState(20) // Change from constant to state
  const [filteredPublications, setFilteredPublications] = useState<Publication[]>([])

  // Filter publications based on active category, price filter, and search query
  const filterPublications = useCallback(() => {
    let filtered: Publication[] = []

    if (activeCategory === "best-sellers") {
      filtered = [...bestSellers]
    } else if (activeCategory === "all") {
      filtered = [...allPublications]
    } else {
      filtered = allPublications.filter((pub) => pub.genres.some((genre) => genre.toLowerCase() === activeCategory))
    }

    // Apply search filter if there's a query
    if (searchQuery.trim() !== "") {
      const query = searchQuery.toLowerCase()
      filtered = filtered.filter(
        (pub) =>
          pub.name.toLowerCase().includes(query) ||
          pub.genres.some((genre) => genre.toLowerCase().includes(query)) ||
          pub.region.toLowerCase().includes(query),
      )
    }

    // Apply price filter only if it's greater than 0
    if (priceFilter > 0) {
      filtered = filtered.filter((pub) => pub.price <= priceFilter)
    }

    return filtered
  }, [activeCategory, searchQuery, priceFilter])

  // Update filtered publications when filters change
  useEffect(() => {
    const filtered = filterPublications()
    setFilteredPublications(filtered)
    setCurrentPage(1) // Reset to page 1 when filters change
  }, [activeCategory, searchQuery, priceFilter, filterPublications])

  // Calculate max price for current category
  useEffect(() => {
    let categoryPublications: Publication[] = []

    if (activeCategory === "best-sellers") {
      categoryPublications = bestSellers
    } else if (activeCategory === "all") {
      categoryPublications = allPublications
    } else {
      categoryPublications = allPublications.filter((pub) =>
        pub.genres.some((genre) => genre.toLowerCase() === activeCategory),
      )
    }

    if (categoryPublications.length > 0) {
      const max = Math.max(...categoryPublications.map((pub) => pub.price))
      setMaxPrice(Math.ceil(max / 100) * 100) // Round up to nearest 100
    }
  }, [activeCategory])

  // Calculate pagination
  const totalPages = Math.max(1, Math.ceil(filteredPublications.length / itemsPerPage))
  const startIndex = (currentPage - 1) * itemsPerPage
  const paginatedPublications = filteredPublications.slice(startIndex, startIndex + itemsPerPage)

  // Update the handlePageChange function to reset to page 1 when items per page changes
  const handlePageChange = (page: number) => {
    if (page < 1 || page > totalPages) return
    setCurrentPage(page)

    // Scroll to top of table
    const tableElement = document.getElementById("publications-table")
    if (tableElement) {
      window.scrollTo({ top: tableElement.offsetTop || 0, behavior: "smooth" })
    }
  }

  // Add this new function to handle items per page change
  const handleItemsPerPageChange = (newItemsPerPage: number) => {
    setItemsPerPage(newItemsPerPage)
    setCurrentPage(1) // Reset to first page when changing items per page
  }

  return (
    <MemberLayout>
      <div>
        <div className="container mx-auto px-4 py-8">
          <h1 className="text-3xl font-bold mb-6">Publications</h1>

          <div className="flex flex-wrap gap-2 mb-8">
            <Link
              href="/publications"
              className="px-4 py-2 rounded-md text-sm font-medium transition-colors bg-green-medium text-white"
            >
              All Publications
            </Link>
            <Link
              href="/publications/specialty"
              className="px-4 py-2 rounded-md text-sm font-medium transition-colors bg-background-tertiary text-text-secondary hover:text-text-primary"
            >
              Specialty Publications
            </Link>
          </div>

          <div className="flex flex-wrap gap-2 mb-8 overflow-x-auto pb-2">
            {categories.map((category) => (
              <button
                key={category.id}
                onClick={() => setActiveCategory(category.id)}
                className={`px-4 py-2 rounded-md text-sm font-medium transition-colors whitespace-nowrap ${
                  activeCategory === category.id
                    ? "bg-green-medium text-white"
                    : "bg-background-tertiary text-text-secondary hover:text-text-primary"
                }`}
              >
                {category.name}
              </button>
            ))}
          </div>

          <div className="flex justify-between items-center mb-6">
            <div className="relative w-full max-w-4xl">
              <input
                type="text"
                placeholder="Search publications..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-background-tertiary border border-border rounded-lg py-3 px-4 text-text-primary focus:outline-none focus:ring-1 focus:ring-green-medium"
              />
            </div>
          </div>

          <PriceFilter defaultValue={0} onChange={setPriceFilter} max={maxPrice} />

          <div id="publications-table" className="overflow-x-auto -mx-4 px-4">
            <div className="min-w-[900px]">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-background-tertiary">
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">PUBLICATION</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">GENRES</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">PRICE</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">DA</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">DR</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">TAT</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">REGION</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">SPONSORED</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">INDEXED</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">DO FOLLOW</th>
                    <th className="py-3 px-4 text-left text-sm font-medium text-text-secondary">ACTION</th>
                  </tr>
                </thead>
                <tbody>
                  {paginatedPublications.length > 0 ? (
                    paginatedPublications.map((pub, index) => (
                      <tr key={index} className="border-b border-border">
                        <td className="py-4 px-4">
                          <div className="flex items-center gap-3">
                            <div className="w-8 h-8 bg-green-medium/30 rounded-md flex items-center justify-center text-green-light font-bold">
                              {pub.initials}
                            </div>
                            <div>{pub.name}</div>
                          </div>
                        </td>
                        <td className="py-4 px-4">
                          <div className="flex flex-wrap gap-1">
                            {pub.genres.map((genre, i) => (
                              <span key={i} className="tag bg-background-tertiary text-text-secondary">
                                {genre}
                              </span>
                            ))}
                          </div>
                        </td>
                        <td className="py-4 px-4">${pub.price}</td>
                        <td className="py-4 px-4">{pub.da}</td>
                        <td className="py-4 px-4">{pub.dr}</td>
                        <td className="py-4 px-4">{pub.tat}</td>
                        <td className="py-4 px-4">{pub.region}</td>
                        <td className="py-4 px-4">
                          <span
                            className={`tag ${
                              pub.sponsored === "Yes" || pub.sponsored === "Discrete"
                                ? "bg-green-medium/30 text-green-light"
                                : "bg-red-500/30 text-red-400"
                            }`}
                          >
                            {pub.sponsored}
                          </span>
                        </td>
                        <td className="py-4 px-4">
                          <span
                            className={`tag ${
                              pub.indexed === "Yes"
                                ? "bg-green-medium/30 text-green-light"
                                : "bg-red-500/30 text-red-400"
                            }`}
                          >
                            {pub.indexed}
                          </span>
                        </td>
                        <td className="py-4 px-4">
                          <span
                            className={`tag ${
                              pub.doFollow === "Yes"
                                ? "bg-green-medium/30 text-green-light"
                                : "bg-red-500/30 text-red-400"
                            }`}
                          >
                            {pub.doFollow}
                          </span>
                        </td>
                        <td className="py-4 px-4">
                          <button className="bg-green-medium hover:bg-green-dark text-white font-semibold py-2 px-4 rounded-md transition-colors text-sm">
                            Buy Now
                          </button>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={11} className="py-8 text-center text-text-secondary">
                        No publications found matching your criteria.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Pagination */}
          {filteredPublications.length > 0 && (
            <div className="flex flex-col md:flex-row justify-between items-center mt-6 gap-4">
              <div className="text-sm text-text-secondary">
                Showing {startIndex + 1}-{Math.min(startIndex + itemsPerPage, filteredPublications.length)} of{" "}
                {filteredPublications.length} publications
              </div>

              <div className="flex flex-wrap items-center gap-4">
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handlePageChange(currentPage - 1)}
                    disabled={currentPage === 1}
                    className="p-2 rounded-md bg-background-tertiary text-text-secondary hover:text-text-primary disabled:opacity-50 disabled:cursor-not-allowed"
                    aria-label="Previous page"
                  >
                    <ChevronLeft className="w-4 h-4" />
                  </button>

                  {/* Page numbers */}
                  <div className="flex items-center gap-1">
                    {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                      // Calculate which page numbers to show
                      let pageNum: number
                      if (totalPages <= 5) {
                        pageNum = i + 1
                      } else if (currentPage <= 3) {
                        pageNum = i + 1
                      } else if (currentPage >= totalPages - 2) {
                        pageNum = totalPages - 4 + i
                      } else {
                        pageNum = currentPage - 2 + i
                      }

                      return (
                        <button
                          key={i}
                          onClick={() => handlePageChange(pageNum)}
                          className={`w-8 h-8 flex items-center justify-center rounded-md text-sm ${
                            currentPage === pageNum
                              ? "bg-green-medium text-white"
                              : "bg-background-tertiary text-text-secondary hover:text-text-primary"
                          }`}
                          aria-label={`Page ${pageNum}`}
                          aria-current={currentPage === pageNum ? "page" : undefined}
                        >
                          {pageNum}
                        </button>
                      )
                    })}
                  </div>

                  <button
                    onClick={() => handlePageChange(currentPage + 1)}
                    disabled={currentPage === totalPages}
                    className="p-2 rounded-md bg-background-tertiary text-text-secondary hover:text-text-primary disabled:opacity-50 disabled:cursor-not-allowed"
                    aria-label="Next page"
                  >
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>

                {/* Items per page selector */}
                <div className="flex items-center gap-2">
                  <span className="text-sm text-text-secondary">Items per page:</span>
                  <select
                    value={itemsPerPage}
                    onChange={(e) => handleItemsPerPageChange(Number(e.target.value))}
                    className="bg-background-tertiary border border-border rounded-md py-1 px-2 text-sm text-text-primary focus:outline-none focus:ring-1 focus:ring-green-medium"
                    aria-label="Select number of items per page"
                  >
                    {itemsPerPageOptions.map((option) => (
                      <option key={option} value={option}>
                        {option}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </MemberLayout>
  )
}
