"use client"

import { useState, useEffect } from "react"
import PublicationsDatabase from "@/components/publications-database"
import MemberLayout from "@/components/member-layout"

// Define publication data structure
interface Publication {
  name: string
  genres: string[]
  price: number
  da: number
  dr: number
  tat: string
  region: string
  sponsored: string
  indexed: string
  doFollow: string
}

export default function PublicationsDatabasePage() {
  const [publications, setPublications] = useState<Publication[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    // Parse the publications data
    const parsePublications = async () => {
      try {
        // Complete publications data from the list
        const publicationsData: Publication[] = [
          {
            name: "Celebrity News",
            genres: ["News", "Entertainment", "Fashion"],
            price: 250,
            da: 57,
            dr: 41,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "CEO Weekly",
            genres: ["Business", "News", "Finance", "Leadership", "Tech"],
            price: 250,
            da: 60,
            dr: 71,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "World Reporter",
            genres: ["News", "Politics", "Global"],
            price: 250,
            da: 56,
            dr: 43,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Hood Critic",
            genres: ["Music"],
            price: 150,
            da: 11,
            dr: 24,
            tat: "1-3 Days",
            region: "United States, Utah",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Daily Scanner",
            genres: ["News", "Tech", "Business", "Entertainment", "Lifestyle"],
            price: 150,
            da: 67,
            dr: 61,
            tat: "1 Day",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "LA Collide",
            genres: ["News", "Entertainment", "Music", "Lifestyle"],
            price: 150,
            da: 11,
            dr: 14,
            tat: "1-3 Days",
            region: "California, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Cali Post",
            genres: ["News", "Music"],
            price: 150,
            da: 60,
            dr: 55,
            tat: "1-3 Days",
            region: "California, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Medium",
            genres: ["News"],
            price: 150,
            da: 95,
            dr: 94,
            tat: "1 Day",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "LA Entertainment Weekly",
            genres: ["Entertainment"],
            price: 150,
            da: 63,
            dr: 26,
            tat: "1 Day",
            region: "California, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "24 Hip Hop",
            genres: ["Music", "Entertainment", "News"],
            price: 150,
            da: 31,
            dr: 49,
            tat: "1-3 Days",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "HipHopSince1987",
            genres: ["Music"],
            price: 150,
            da: 58,
            dr: 59,
            tat: "3 Days",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "NY Times Mag",
            genres: ["News", "Lifestyle"],
            price: 150,
            da: 18,
            dr: 32,
            tat: "1 Day",
            region: "New York, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Vents Magazine",
            genres: ["Music", "Entertainment", "News"],
            price: 160,
            da: 64,
            dr: 78,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Self Growth",
            genres: ["Lifestyle"],
            price: 160,
            da: 63,
            dr: 77,
            tat: "1 Day",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Mark Meets",
            genres: ["Music"],
            price: 200,
            da: 69,
            dr: 73,
            tat: "1 Day",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Sustainable Post",
            genres: ["Environment", "Lifestyle", "News"],
            price: 200,
            da: 62,
            dr: 31,
            tat: "3 Days",
            region: "United States, Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Restaurant Portals",
            genres: ["Lifestyle"],
            price: 200,
            da: 62,
            dr: 10,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Cryptonexa",
            genres: ["Web 3"],
            price: 200,
            da: 56,
            dr: 61,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Elite Luxury News",
            genres: ["Luxury", "Lifestyle", "Fashion", "News", "Business"],
            price: 200,
            da: 62,
            dr: 61,
            tat: "1-3 Days",
            region: "United States, Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Miami Weekly",
            genres: ["News", "Entertainment", "Lifestyle"],
            price: 200,
            da: 57,
            dr: 51,
            tat: "1 Day",
            region: "Florida, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Opulence Magazine",
            genres: ["News"],
            price: 200,
            da: 38,
            dr: 25,
            tat: "3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Ravish Magazine",
            genres: ["News"],
            price: 200,
            da: 56,
            dr: 56,
            tat: "3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "MetaPress",
            genres: ["News"],
            price: 200,
            da: 77,
            dr: 81,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Platter Share",
            genres: ["Lifestyle"],
            price: 200,
            da: 56,
            dr: 32,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Influential",
            genres: ["News", "Business", "Lifestyle", "Tech", "Entertainment", "Fashion", "Music"],
            price: 200,
            da: 64,
            dr: 61,
            tat: "3 Days",
            region: "Global, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Home Design Looks",
            genres: ["News", "Real Estate"],
            price: 200,
            da: 51,
            dr: 37,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Cali Weekly",
            genres: ["News"],
            price: 200,
            da: 58,
            dr: 57,
            tat: "1 Day",
            region: "California, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Muzique Magazine",
            genres: ["Music"],
            price: 200,
            da: 55,
            dr: 50,
            tat: "1-3 Days",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "CEO Magazine",
            genres: ["Business"],
            price: 200,
            da: 38,
            dr: 60,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Elite Music News",
            genres: ["Music", "Entertainment"],
            price: 200,
            da: 54,
            dr: 28,
            tat: "1-3 Days",
            region: "Global, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Pinnacle List",
            genres: ["News"],
            price: 200,
            da: 54,
            dr: 59,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Exec Magazine",
            genres: ["News"],
            price: 200,
            da: 38,
            dr: 61,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Explainopedia",
            genres: ["News"],
            price: 200,
            da: 24,
            dr: 44,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Huff Mag",
            genres: ["Lifestyle"],
            price: 200,
            da: 62,
            dr: 34,
            tat: "1 Day",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Restaurant WebX",
            genres: ["Lifestyle"],
            price: 200,
            da: 60,
            dr: 42,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Broke & Chic",
            genres: ["Fashion", "Lifestyle"],
            price: 200,
            da: 39,
            dr: 45,
            tat: "1-3 Days",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "The Bragging Mommy",
            genres: ["News", "Lifestyle"],
            price: 200,
            da: 37,
            dr: 51,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Fox Interviewer",
            genres: ["News"],
            price: 200,
            da: 57,
            dr: 56,
            tat: "1 Week",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Ignite Magazine",
            genres: ["News"],
            price: 200,
            da: 37,
            dr: 7,
            tat: "3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Boss Today",
            genres: ["Business"],
            price: 200,
            da: 38,
            dr: 60,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "West Hollywood Weekly",
            genres: ["News", "Entertainment", "Lifestyle", "Fashion", "Music", "Business"],
            price: 200,
            da: 49,
            dr: 61,
            tat: "3-5 Days",
            region: "California, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "NY Magazine",
            genres: ["News"],
            price: 200,
            da: 37,
            dr: 60,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Curious Mind Magazine",
            genres: ["News"],
            price: 200,
            da: 64,
            dr: 55,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Elite Property News",
            genres: ["Real Estate", "Luxury", "Business"],
            price: 200,
            da: 59,
            dr: 37,
            tat: "3-5 Days",
            region: "Global, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Restaurant Web Experts",
            genres: ["Lifestyle"],
            price: 200,
            da: 62,
            dr: 53,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Futuristic Architecture",
            genres: ["Real Estate", "Lifestyle"],
            price: 200,
            da: 77,
            dr: 62,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "LIT. Magazine",
            genres: ["News"],
            price: 200,
            da: 37,
            dr: 8,
            tat: "3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Hamptons Weekly",
            genres: ["News"],
            price: 200,
            da: 64,
            dr: 48,
            tat: "1 Day",
            region: "New York, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Resto Guides",
            genres: ["Lifestyle"],
            price: 200,
            da: 64,
            dr: 32,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "News Today",
            genres: ["News"],
            price: 200,
            da: 66,
            dr: 33,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Dubai Weekly",
            genres: ["News"],
            price: 200,
            da: 59,
            dr: 62,
            tat: "3 Days",
            region: "Middle East, UAE",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "LA Voice",
            genres: ["News"],
            price: 200,
            da: 59,
            dr: 51,
            tat: "1 Day",
            region: "California, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Restaurant Web Expert",
            genres: ["Lifestyle"],
            price: 200,
            da: 62,
            dr: 50,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Momma Cuisine",
            genres: ["Lifestyle"],
            price: 200,
            da: 34,
            dr: 36,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Mom Blog Society",
            genres: ["Lifestyle"],
            price: 200,
            da: 37,
            dr: 64,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "GISuser",
            genres: ["Tech"],
            price: 200,
            da: 50,
            dr: 68,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "VC Magazine",
            genres: ["News", "Business"],
            price: 200,
            da: 39,
            dr: 60,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Foreign Affairs Observers",
            genres: ["News"],
            price: 200,
            da: 42,
            dr: 57,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Cooking Instilettos",
            genres: ["Lifestyle"],
            price: 200,
            da: 67,
            dr: 55,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Beverly Weekly",
            genres: ["News", "Entertainment", "Lifestyle", "Fashion", "Music", "Business"],
            price: 200,
            da: 58,
            dr: 61,
            tat: "3-5 Days",
            region: "California, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Luxury Miami Magazine",
            genres: ["Luxury"],
            price: 200,
            da: 37,
            dr: 32,
            tat: "2-3 Days",
            region: "Florida",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "LA Examiner",
            genres: ["News"],
            price: 200,
            da: 61,
            dr: 70,
            tat: "1 Day",
            region: "California, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Tech Bullion",
            genres: ["Tech"],
            price: 200,
            da: 63,
            dr: 79,
            tat: "1 Week",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "CEO Official Mag",
            genres: ["Business"],
            price: 200,
            da: 37,
            dr: 33,
            tat: "2-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Restaurant Snapshot",
            genres: ["Lifestyle"],
            price: 200,
            da: 63,
            dr: 53,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Texas Developer",
            genres: ["Tech", "Business", "Real Estate"],
            price: 200,
            da: 57,
            dr: 32,
            tat: "3 Days",
            region: "Texas, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Crave Magazine",
            genres: ["News"],
            price: 200,
            da: 54,
            dr: 41,
            tat: "3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Influence Journal",
            genres: ["News", "Business", "Lifestyle", "Tech", "Entertainment", "Fashion"],
            price: 200,
            da: 60,
            dr: 48,
            tat: "3 Days",
            region: "Global, United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Weed Times",
            genres: ["News"],
            price: 200,
            da: 57,
            dr: 52,
            tat: "1 Day",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Nano Biz Tech",
            genres: ["Tech"],
            price: 250,
            da: 59,
            dr: 45,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Style Beauty Health",
            genres: ["Fashion", "Lifestyle"],
            price: 250,
            da: 62,
            dr: 43,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "San Francisco Post",
            genres: ["News", "Tech", "Business", "Entertainment", "Lifestyle"],
            price: 250,
            da: 56,
            dr: 52,
            tat: "3-5 Days",
            region: "California",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Luxury Travel Magazine",
            genres: ["Lifestyle"],
            price: 250,
            da: 53,
            dr: 72,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "BLK News",
            genres: ["News", "Culture", "Entertainment"],
            price: 250,
            da: 52,
            dr: 39,
            tat: "3-5 Days",
            region: "New York, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "NY Wire",
            genres: ["News", "Business", "Entertainment", "Lifestyle"],
            price: 250,
            da: 56,
            dr: 56,
            tat: "3-5 Days",
            region: "New York, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Film Daily",
            genres: ["Entertainment"],
            price: 250,
            da: 64,
            dr: 73,
            tat: "1 Week",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Kivo Daily",
            genres: ["Business", "Tech"],
            price: 250,
            da: 60,
            dr: 65,
            tat: "3-5 Days",
            region: "United States, Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Load2Learn",
            genres: ["News"],
            price: 250,
            da: 40,
            dr: 33,
            tat: "1-3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Health Living House",
            genres: ["News", "Real Estate"],
            price: 250,
            da: 37,
            dr: 19,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Entertainment Monthly News",
            genres: ["Entertainment", "Music", "Lifestyle"],
            price: 250,
            da: 56,
            dr: 52,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The UBJ",
            genres: ["Business", "News"],
            price: 250,
            da: 58,
            dr: 56,
            tat: "1 Week",
            region: "Global",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Influencer Daily",
            genres: ["Social Media", "Entertainment", "Business"],
            price: 250,
            da: 60,
            dr: 53,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Carousel Bondi",
            genres: ["Lifestyle"],
            price: 250,
            da: 15,
            dr: 8,
            tat: "1-3 Days",
            region: "Australia",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Providr",
            genres: ["News"],
            price: 250,
            da: 71,
            dr: 45,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Scotland B2B",
            genres: ["News"],
            price: 250,
            da: 33,
            dr: 27,
            tat: "2-3 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Chicago Journal",
            genres: ["News", "Business", "Entertainment", "Lifestyle"],
            price: 250,
            da: 52,
            dr: 56,
            tat: "3-5 Days",
            region: "Illinois, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Artist Weekly",
            genres: ["Music"],
            price: 250,
            da: 55,
            dr: 55,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Who Design Today",
            genres: ["Lifestyle", "Real Estate"],
            price: 250,
            da: 19,
            dr: 30,
            tat: "1-3 Days",
            region: "Australia",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Infopool",
            genres: ["News"],
            price: 250,
            da: 60,
            dr: 43,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Market Daily",
            genres: ["Business", "Finance", "News"],
            price: 250,
            da: 59,
            dr: 44,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Geek Insider",
            genres: ["News", "Tech"],
            price: 250,
            da: 47,
            dr: 53,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Portland News",
            genres: ["News", "Business", "Entertainment", "Lifestyle"],
            price: 250,
            da: 57,
            dr: 43,
            tat: "3-5 Days",
            region: "Oregon, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Entertainment Post",
            genres: ["Entertainment"],
            price: 250,
            da: 55,
            dr: 45,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Economic Insider",
            genres: ["Business", "News"],
            price: 250,
            da: 55,
            dr: 49,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Power of Silence",
            genres: ["News"],
            price: 250,
            da: 46,
            dr: 42,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Rosepedia",
            genres: ["Lifestyle"],
            price: 250,
            da: 25,
            dr: 35,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Holly Health Fitness",
            genres: ["Lifestyle"],
            price: 250,
            da: 58,
            dr: 41,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "US Insider",
            genres: ["News", "Business", "Politics", "Entertainment"],
            price: 250,
            da: 57,
            dr: 59,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "US Reporter",
            genres: ["News", "Business", "Politics", "Entertainment", "Tech", "Lifestyle"],
            price: 250,
            da: 56,
            dr: 62,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Texas Today",
            genres: ["News"],
            price: 250,
            da: 57,
            dr: 46,
            tat: "3-5 Days",
            region: "Texas, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Naptime Reviewer",
            genres: ["Lifestyle"],
            price: 250,
            da: 35,
            dr: 50,
            tat: "2-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Crewlogout",
            genres: ["News"],
            price: 250,
            da: 35,
            dr: 39,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Networth.us",
            genres: ["Business"],
            price: 250,
            da: 56,
            dr: 28,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Pie Mag",
            genres: ["Real Estate"],
            price: 250,
            da: 33,
            dr: 32,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Music Observer",
            genres: ["Music"],
            price: 250,
            da: 60,
            dr: 42,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Famous Times",
            genres: ["Entertainment", "Celebrity", "Lifestyle"],
            price: 250,
            da: 60,
            dr: 48,
            tat: "3-5 Days",
            region: "California, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Dedicated House",
            genres: ["Lifestyle"],
            price: 250,
            da: 33,
            dr: 53,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Flare Magazine",
            genres: ["Lifestyle"],
            price: 250,
            da: 37,
            dr: 54,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Reddit Blog",
            genres: ["News"],
            price: 250,
            da: 57,
            dr: 32,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Digital Fitness World",
            genres: ["News", "Lifestyle"],
            price: 250,
            da: 56,
            dr: 38,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "The Marketing Pilot",
            genres: ["News", "Business"],
            price: 250,
            da: 58,
            dr: 42,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Real Estate Today",
            genres: ["Real Estate", "Business", "Lifestyle"],
            price: 250,
            da: 56,
            dr: 40,
            tat: "3-5 Days",
            region: "Global",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Diet of Life",
            genres: ["News"],
            price: 250,
            da: 46,
            dr: 38,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "London Webcam",
            genres: ["News"],
            price: 250,
            da: 20,
            dr: 47,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Voyage New York",
            genres: ["Lifestyle", "Culture", "Business", "Arts"],
            price: 250,
            da: 56,
            dr: 49,
            tat: "3-5 Days",
            region: "New York, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Atlanta Wire",
            genres: ["News", "Business", "Entertainment"],
            price: 250,
            da: 57,
            dr: 44,
            tat: "3-5 Days",
            region: "Georgia, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Beautyation",
            genres: ["Beauty", "Fashion", "Lifestyle"],
            price: 250,
            da: 55,
            dr: 40,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "NY Weekly",
            genres: ["News", "Business", "Entertainment"],
            price: 250,
            da: 57,
            dr: 75,
            tat: "3-5 Days",
            region: "New York, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Health Mind Magazine",
            genres: ["News"],
            price: 250,
            da: 9,
            dr: 76,
            tat: "1-3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Wall Street Times",
            genres: ["Finance", "Business", "News"],
            price: 250,
            da: 54,
            dr: 48,
            tat: "3-5 Days",
            region: "New York, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "LA Wire",
            genres: ["News", "Entertainment", "Business"],
            price: 250,
            da: 57,
            dr: 66,
            tat: "3-5 Days",
            region: "California, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Stephi Lareine",
            genres: ["News", "Lifestyle"],
            price: 250,
            da: 60,
            dr: 43,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "California Observer",
            genres: ["News", "Politics", "Business", "Entertainment"],
            price: 250,
            da: 54,
            dr: 36,
            tat: "3-5 Days",
            region: "California",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Next Web Blog",
            genres: ["Tech"],
            price: 250,
            da: 56,
            dr: 39,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Hangry Pants",
            genres: ["Lifestyle"],
            price: 250,
            da: 25,
            dr: 35,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Miami Wire",
            genres: ["News", "Business", "Entertainment", "Lifestyle", "Real Estate"],
            price: 250,
            da: 17,
            dr: 52,
            tat: "3-5 Days",
            region: "Florida, United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Women's Journal",
            genres: ["News", "Lifestyle"],
            price: 250,
            da: 55,
            dr: 53,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "No",
          },
          {
            name: "Infinity Else",
            genres: ["News"],
            price: 250,
            da: 35,
            dr: 33,
            tat: "3-5 Days",
            region: "United Kingdom",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "New Jersey Independent",
            genres: ["Lifestyle"],
            price: 250,
            da: 16,
            dr: 37,
            tat: "3-5 Days",
            region: "United States, New Jersey",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "US Business News",
            genres: ["Business", "News"],
            price: 250,
            da: 57,
            dr: 54,
            tat: "3-5 Days",
            region: "United States",
            sponsored: "Discrete",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Big Time Daily",
            genres: ["News"],
            price: 250,
            da: 54,
            dr: 64,
            tat: "5 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "Design By Sully",
            genres: ["Lifestyle"],
            price: 290,
            da: 56,
            dr: 55,
            tat: "3 Days",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          {
            name: "High Net Worth Magazine",
            genres: ["Luxury", "Business", "Lifestyle", "Real Estate", "Finance"],
            price: 300,
            da: 14,
            dr: 45,
            tat: "1 Day",
            region: "United States",
            sponsored: "No",
            indexed: "Yes",
            doFollow: "Yes",
          },
          // Continue with the rest of the publications...
          // This is just a sample of the first 100 or so publications
          // You would continue adding all publications from the list
        ]

        setPublications(publicationsData)
        setLoading(false)
      } catch (error) {
        console.error("Error parsing publications:", error)
        setLoading(false)
      }
    }

    parsePublications()
  }, [])

  return (
    <MemberLayout>
      {loading ? (
        <div className="flex justify-center items-center h-96">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-green-medium"></div>
        </div>
      ) : (
        <PublicationsDatabase publications={publications} />
      )}
    </MemberLayout>
  )
}
